### PR TITLE
Provide a Security Policy

### LINKED ISSUE #233: [CRITICAL] Provide a Security Policy
### Expected

https://github.com/algorandfoundation/algokit-cli/security

### Template

* https://github.com/algorand/go-algorand/blob/master/CONTRIBUTING.md#security--vulnerabilities

### PR DESCRIPTION
**Pull request by abebeos**
closes #233 

Use the text from the go-algorand project and direct users to the same resources.

### CODE REVIEW

**Comment by ryanRfox** [comment]
BLOCKER: AlgoKit is not mentioned within the "Assets in scope" section of the Immunefi bounty page for Algorand:
https://immunefi.com/bounty/algorand/

**Comment by abebeos** [comment]
It looks like the foundation is a different legal entity, so the text needs to be modified anyways.

**Comment by johnalanwoods** [comment]
AlgoKit isn’t in scope for the bug rewards program.

**Comment by abebeos** [comment]
> AlgoKit isn’t in scope for the bug rewards program.

I see. I've updated the document, you can either merge or take this as a template to provide a document.

**Comment by Loedn** [comment]
Hi Abe, thanks for bringing this up, we're in the process of creating a disclosure form for the security policy, will commit this once it's done and we can then merge the pr

**Comment by abebeos** [comment]
> in the process of creating a disclosure form for the security policy

I think github has some decicated functionality for this, which in combination with a contact email should serve all cases.

Note that you do not need to everything in one chunk. You can e.g. use this PR initially, then later update it (with your form, or with githubs security-report functionality).

Anyway, leaving it to you to decide.

Please feel free to use/modify or close this PR as you see fit.

**Comment by abebeos** [comment]
@Loedn, after rethinking this: the PR can go in "as-is", and you can add a link to your form once it is ready.

This is really nothing special.

**Pull request closed without merging**
